#pragma config(Motor,  port2,           LeftSides,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LeftMid,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           RightSides,    tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           RightMid,      tmotorVex393HighSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           Tower1,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           Tower2,        tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           MobileGoal,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	/* Autonomous plan: TBD
	 *
	*/
  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
  	/*
  	 * Basic Tank Controls
  	 *
  	 * RightSides - Controls the FrontRight and BackRight motors.
  	 * LeftSides - Controls the FrontLeft and BackLeft motors.
  	 * LeftMid & RightMid Reversed due to build configuration.
  	 */

		//Left side
		motor[LeftSides] = vexRT[Ch3]; //Assigns Left side motors to left joystick
		motor[LeftMid] = vexRT[Ch3]; //Assigns Left mid motor to left joystick

		//Right Side
		motor[RightSides] = vexRT[Ch2]; //Assigns Right side motors to right joystick
		motor[RightMid] = vexRT[Ch2]; //Assigns Right mid motor to right joystick

		//---- Manipulator Control - WIP --------------------------------------//

		//Claw Controls
		motor[Claw] = vexRT[Btn8D]*127 + vexRT[Btn8R]*-127; //Right (8) side claw control

		//Tower Control
		motor[Tower1] = vexRT[Btn6U]*127 + vexRT[Btn6D]*-127; //Tower Control using right bumpers
		motor[Tower2] = vexRT[Btn6U]*127 + vexRT[Btn6D]*-127;

		//Mobile Goal Pickup
		motor[MobileGoal] = vexRT[Btn5D]*-127 + vexRT[Btn5U]*127; //Pickup control using left bumpers
  }
}
