#pragma config(Motor,  port1,           RightFront,    tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RightMid,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightBack,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftFront,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           LeftMid,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LeftBack,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           Mobile,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LeftTower,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightTower,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  bLCDBacklight = true;
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
int autover = 1;
task autonomous()
{
//Extend Mobile Goal Pickup
motor[Mobile] = -127;
wait1Msec(700);
motor[Mobile] = 0;
//-----------------//

// Moves forward to Mobile Goal on Parking Location
motor[LeftFront] = 127;
motor[LeftMid] = 127;
motor[LeftBack] = 127;
motor[RightFront] = 77; //73
motor[RightMid] = 77;
motor[RightBack] = 77;
wait1Msec(3100); //Waits to continue for 1.35s
motor[LeftFront] = 0;
motor[LeftMid] = 0;
motor[LeftBack] = 0;
motor[RightFront] = 0;
motor[RightMid] = 0;
motor[RightBack] = 0;
//------------------//

//Retracts Mobile Goal Pickup

motor[Mobile] = 127;
wait1Msec(700);
motor[Mobile] = 0;
//-----------------//

//Moves to Start
motor[LeftFront] = -127;
motor[LeftMid] = -127;
motor[LeftBack] = -127;
motor[RightFront] = -77;
motor[RightMid] = -77;
motor[RightBack] = -77;
wait1Msec(3000);
motor[LeftFront] = 0;
motor[LeftMid] = 0;
motor[LeftBack] = 0;
motor[RightFront] = 0;
motor[RightMid] = 0;
motor[RightBack] = 0;
//----------------//

//Turns Around
motor[LeftFront] = 127;
motor[LeftMid] = 127;
motor[LeftBack] = 127;
motor[RightFront] = -77;
motor[RightMid] = -77;
motor[RightBack] = -77;
wait1Msec(1550);
motor[LeftFront] = 0;
motor[LeftMid] = 0;
motor[LeftBack] = 0;
motor[RightFront] = 0;
motor[RightMid] = 0;
motor[RightBack] = 0;
//-----------------//

//Makes Left Side Allign with 10pt bar
motor[LeftFront] = 127;
motor[LeftMid] = 127;
motor[LeftBack] = 127;
wait1Msec(800);
motor[LeftFront] = 0;
motor[LeftMid] = 0;
motor[LeftBack] = 0;
//--------------------//

//Extend Mobile Goal Pickup
motor[Mobile] = -127;
wait1Msec(700);
motor[Mobile] = 0;

//Moves In Reverse
motor[LeftFront] = -127;
motor[LeftMid] = -127;
motor[LeftBack] = -127;
motor[RightFront] = -77;
motor[RightMid] = -77;
motor[RightBack] = -77;
wait1Msec(500);
motor[LeftFront] = 0;
motor[LeftMid] = 0;
motor[LeftBack] = 0;
motor[RightFront] = 0;
motor[RightMid] = 0;
motor[RightBack] = 0;
//------------------//
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  //Plans for this bot:
	//	- LCD Display, needs further testing, start with basic battery voltage display.
	//	- Quad Encoders, will require further testing before implementation

  while (true)
  {
  		int mgp = -1;
  		//---- Drive-Train Control -------------------------------------------//

			//Left side - Normal Speed
			motor[LeftFront] = vexRT[Ch3]; //Assigns Left Front motor to left joystick
			motor[LeftMid] = vexRT[Ch3]; //Assigns Left Mid motor to left joystick
			motor[LeftBack] = vexRT[Ch3]; //Assigns Left Back motor to left joystick

			//Right Side Speed Modifications due to inbalance of motor speed on Drivetrain.
			if(vexRT[Ch2]>75) { //While the Joystick is greater than 77, max motor speed is 77.
				motor[RightFront] = 75;
				motor[RightMid] = 75;
				motor[RightBack] = 75;
			}
			if(vexRT[Ch2]<-75) { //While Joystick is lower than -77, minimum motor speed is -77.
				motor[RightFront] = -75;
				motor[RightMid] = -75;
				motor[RightBack] = -75;
			}
			if(vexRT[Ch2] < 75 && vexRT[Ch2] > -75) { //Instead of Else statements, which conflict with code, using an if statement for the normal control setup.
				motor[RightFront] = vexRT[Ch2];
				motor[RightMid] = vexRT[Ch2];
				motor[RightBack] = vexRT[Ch2];
		}
			//---- Manipulator Control - WIP --------------------------------------//

			//Claw Controls
			motor[Claw] = vexRT[Btn8R]*127 + vexRT[Btn8D]*-127; //Right (8) side claw control

			//Tower Control
			motor[LeftTower] = vexRT[Btn6U]*127 + vexRT[Btn6D]*-127; //Tower Control using right bumpers
			motor[RightTower] = vexRT[Btn6U]*127 + vexRT[Btn6D]*-127;

			//Mobile Goal Pickup
			motor[Mobile] = vexRT[Btn5U]*-127 + vexRT[Btn5D]*127; //Pickup control using left bumpers. Up goes out, down goes in.

			//Testing a Toggle Switch for Mobile Goal Pickup.

			//Pressed once, it lowers, pressed again, it raises... Hopefully this works.
			if(mgp == 1 && vexRT[Btn7U] == 1 && vexRT[Btn8U] == 0) { // Extra conditions ensure only happens if the button is pressed.
				motor[Mobile] = 127;
				wait1Msec(700);
				motor[Mobile] = 0;
				mgp = -1;
			}

			if(mgp == -1 && vexRT[Btn7U] == 1 && vexRT[Btn8U] == 0) {
				motor[Mobile] = -127;
				wait1Msec(700);
				motor[Mobile] = 0;
				mgp = 1;
			}
			//---- Autonomous Test Function ---------------------------------------//
			if(vexRT[Btn8U] == 1) { //If both buttons 8U and 7U are pressed simultaneously, run the autonomous() task
				if(vexRT[Btn7U] == 1) {

					//Extend Mobile Goal Pickup
					motor[Mobile] = -127;
					wait1Msec(700);
					motor[Mobile] = 0;
					//-----------------//

					// Moves forward to Mobile Goal on Parking Location
					motor[LeftFront] = 127;
					motor[LeftMid] = 127;
					motor[LeftBack] = 127;
					motor[RightFront] = 77; //73
					motor[RightMid] = 77;
					motor[RightBack] = 77;
					wait1Msec(3100); //Waits to continue for 1.35s
					motor[LeftFront] = 0;
					motor[LeftMid] = 0;
					motor[LeftBack] = 0;
					motor[RightFront] = 0;
					motor[RightMid] = 0;
					motor[RightBack] = 0;
					//------------------//

					//Retracts Mobile Goal Pickup

					motor[Mobile] = 127;
					wait1Msec(700);
					motor[Mobile] = 0;
					//-----------------//

					//Moves to Start
					motor[LeftFront] = -127;
					motor[LeftMid] = -127;
					motor[LeftBack] = -127;
					motor[RightFront] = -77;
					motor[RightMid] = -77;
					motor[RightBack] = -77;
					wait1Msec(3000);
					motor[LeftFront] = 0;
					motor[LeftMid] = 0;
					motor[LeftBack] = 0;
					motor[RightFront] = 0;
					motor[RightMid] = 0;
					motor[RightBack] = 0;
					//----------------//

					//Turns Around
					motor[LeftFront] = 127;
					motor[LeftMid] = 127;
					motor[LeftBack] = 127;
					motor[RightFront] = -77;
					motor[RightMid] = -77;
					motor[RightBack] = -77;
					wait1Msec(1550);
					motor[LeftFront] = 0;
					motor[LeftMid] = 0;
					motor[LeftBack] = 0;
					motor[RightFront] = 0;
					motor[RightMid] = 0;
					motor[RightBack] = 0;
					//-----------------//

					//Makes Left Side Allign with 10pt bar
					motor[LeftFront] = 127;
					motor[LeftMid] = 127;
					motor[LeftBack] = 127;
					wait1Msec(800);
					motor[LeftFront] = 0;
					motor[LeftMid] = 0;
					motor[LeftBack] = 0;
					//--------------------//

					//Extend Mobile Goal Pickup
					motor[Mobile] = -127;
					wait1Msec(700);
					motor[Mobile] = 0;

					//Moves In Reverse
					motor[LeftFront] = -127;
					motor[LeftMid] = -127;
					motor[LeftBack] = -127;
					motor[RightFront] = -77;
					motor[RightMid] = -77;
					motor[RightBack] = -77;
					wait1Msec(500);
					motor[LeftFront] = 0;
					motor[LeftMid] = 0;
					motor[LeftBack] = 0;
					motor[RightFront] = 0;
					motor[RightMid] = 0;
					motor[RightBack] = 0;
					//------------------//

					//Testing autonomous selection variable is autover
			}
		}

		//---- LCD Display Test -----------------------------------------------//
		float batlevel = nAvgBatteryLevel/1000;
		//Sets batlevel to the battery level

		int btnPressed = nLCDButtons;

		clearLCDLine(0);
		clearLCDLine(1);
		//Resets LCD Display

		displayLCDString(0, 1, "1264B Battery: ");
		displayLCDNumber(0, 17, batlevel);
		//Displays battery level on the top line

		displayLCDString(1, 1, "Autonomous Version: ");
		displayLCDNumber(1, 21, autover);
		//Setup for Autonomous selection

		if(btnPressed == 1) { //If the left button is pressed, scroll left on autonomous versions
			autover = autover - 1;
			wait1Msec(200); //Buffer for time
		}

		if(btnPressed == 4) { //If the right button is pressed, scroll right on autonomous versions
			autover = autover + 1;
			wait1Msec(200); //Buffer for time
		}
  }
}
