#pragma config(Sensor, in1,    PEPower,        sensorAnalog)
#pragma config(Sensor, dgtl9,  LedRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, LedYel,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, LedGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LedFull,        sensorLEDtoVCC)
#pragma config(Motor,  port1,           ArmRight,      tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           RightBack,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LeftBack,      tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           BRightTower,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           FRightTower,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           FLeftTower,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           BLeftTower,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           RightFront,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftFront,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          ArmLeft,       tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
/*--------------------------------------------------------------------------------------------------//
//																																																  //
//		Credits:                                                                                      //
//		Drive-Control: Carmen Morgan                                                                  //
//		Autonomous: Logan Housden, Carmen Morgan, Jordan                                              //
//		Sensors: Logan Housden                                                                        //
//																																																  //
//--------------------------------------------------------------------------------------------------*/

//Variables //
char auto1String[] = "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
char auto2String[] = "abcdefghijk";
char auto3String[] = "abcdefghijk";
char auto4String[] = "abcdefghijk";
char auto5String[] = "abcdefghijk";
char auto6String[] = "abcdefghijk";
char auto7String[] = "abcdefghijk";
char auto8String[] = "abcdefghijk";
int autostart=0;
int auto=0; //Determines selected autonomous; starts off disabled.
int autoselect;
int automin = 0; //Minimum value for autonomous scrolling
int automax = 8; //Maximum value for autonomous scrolling

int screen = 0;
float powerlevelCortex;
float powerlevelExpander;
float power; //Power Expander power level

float etime; //Expander time(used with batterylevel()
float ctime; //Cortex time(used with batterylevel()
int recordTime=15;
bool recordMode = false; //Controls Autonomous Recording
bool debug = false; //Controls Debug toggle
int ledmode = 1; //Controls LED mode

// int count = 0; //For Record & Play
// Power Level
// Full = 1
// Good = .75
// OK   = .5
// Bad  = .25

//////////////

// ---------- Functions ---------- //
//function cap is 256, do not exceed this limit

//Record & Play -Jordan & Logan- //

//void recordAuto(char character) {
//	if (recordMode && debug) {
//		writeDebugStreamLine("autoString[%d] = '%c';",count ,character);
//		count++;
//	}
//}

//Autonomous Recording Function - Jordan
void recordAuto(char character) {
	if(recordMode && debug) {
		writeDebugStream("%c",character);
	}
}
//Battery Control Function - Carmen & Logan
void batterylevel(float desiredTime) { //cpwr = Cortex power, epwr = Expander power
	ctime=desiredTime*(1+(1-powerlevelCortex)); //AT=DT*(1+(1-BL)
	etime=desiredTime*(1+(1-powerlevelExpander));
}
//Movement Control Functions - Carmen & Logan
void move_pivot_turn(int time, int power) { //Right Turn in place (pos. power = left, neg. = right) ---> 90 degree turn
	batterylevel(time);
	motor[LeftFront] = power;
	motor[LeftBack] = power;
	motor[RightFront] = power*-1;
	motor[RightBack] = power*-1;
	wait1Msec(ctime*1000);
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;
	motor[RightFront] = 0;
	motor[RightBack] = 0;
}
void move_swing_turn(int time, int lpower, int rpower) { //Adjustable Angle Turns (allows for swing turns by setting one value higher than the other)
	batterylevel(time);
	motor[LeftFront] = lpower;
	motor[LeftBack] = lpower;
	motor[RightFront] = rpower;
	motor[RightBack] = rpower;
	wait1Msec(etime*1000);
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;
	motor[RightFront] = 0;
	motor[RightBack] = 0;
}

void move_straight(int time, int power) { //Move straight (positive for forward, negative for reverse)
	batterylevel(time);
	motor[LeftFront] = power;
	motor[LeftBack] = power;
	motor[RightFront] = power;
	motor[RightBack] = power;
	wait1Msec(etime*1000);
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;
	motor[RightFront] = 0;
	motor[RightBack] = 0;
}
void moveLeft(int lpower) { //Drive control.
	motor[LeftFront] = lpower;
	motor[LeftBack] = lpower;
}
void moveRight(int rpower) {
	motor[RightFront] = rpower;
	motor[RightBack] = rpower;
}

void manipulator_tower(int power) { //Raise/Lower Arm Tower
	motor[FLeftTower] = power;
	motor[BLeftTower] = power;
	motor[BRightTower] = power;
	motor[FRightTower] = power;
}

void manipulator_arm(int power) { //Raise/Lower Arm
	motor[ArmLeft] = power;
	motor[ArmRight] = power;
}
//Dab Function (Why?) - Carmen
void dab(int time, int power) {
	batterylevel(time);
	move_pivot_turn(etime*1000, power);
	move_pivot_turn(etime*1000, -power);
	move_swing_turn(etime*1000, power, power*-1);
}
//Autonomous Interpret Function - Jordan
void interpretAuto(char *myAutoString) { //Need to move this down.
	int i;
	for (i = 0; i < strlen(myAutoString); i++) {
		switch(myAutoString[i]) {
		case 'a':
			manipulator_tower(127);
			break;
		case 'b':
			manipulator_tower(-127);
			break;
		case 'c':
			manipulator_tower(0);
		case 'd':
			moveLeft(127);
			break;
		case 'e':
			moveLeft(-127);
			break;
		case 'f':
			moveRight(127);
			break;
		case 'g':
			moveRight(-127);
			break;
		case 'h':
			moveLeft(0);
			moveRight(0);
			break;
		case 'i':
			manipulator_arm(30);
			break;
		case 'j':
			manipulator_arm(-90);
			break;
		case 'k':
			manipulator_arm(0);
			break;
		}
	}
}
//LED State Function - Logan (Idea: Jordan)
void led_state(int led1, int led2, int led3, int led4) { //Sets LEDs to specified value.
	/*
	| 0 = Off
	| 1 = On/Solid
	| 2 = On/Blink
	| 3 = Unchanged
	*/
	if(led1==0) { //Controls LedFull
		SensorValue[LedFull]=0;
		} else if(led1==1) {
		SensorValue[LedFull]=1;
		} else if(led1==2) {
		SensorValue[LedFull]=1;
		wait1Msec(500);
		SensorValue[LedFull]=0;
		wait1Msec(500);
		} else if(led1==3) {
	}

	if(led2==0) { //Controls LedGreen
		SensorValue[LedGreen]=0;
		} else if(led2==1) {
		SensorValue[LedGreen]=1;
		} else if(led2==2) {
		SensorValue[LedGreen]=1;
		wait1Msec(500);
		SensorValue[LedGreen]=0;
		wait1Msec(500);
		} else if(led2==3) {
	}

	if(led3==0) { //Controls LedYel
		SensorValue[LedYel]=0;
		} else if(led3==1) {
		SensorValue[LedYel]=1;
		} else if(led3==2) {
		SensorValue[LedYel]=1;
		wait1Msec(500);
		SensorValue[LedYel]=0;
		wait1Msec(500);
		} else if(led3==3) {
	}

	if(led4==0) { //Controls LedRed
		SensorValue[LedRed]=0;
		} else if(led4==1) {
		SensorValue[LedRed]=1;
		}else if(led4==2) {
		SensorValue[LedRed]=1;
		wait1Msec(500);
		SensorValue[LedRed]=0;
		wait1Msec(500);
		} else if(led4==3) {
	}
}

//Tasks// - Ensure that scheduler is the lowest user-created task
//Autonomous LED Control - Logan
task autoled { //Controls autonomous mode LED states
	ledmode=1;
	while(ledmode==1) {
		switch(auto) {
		case 0:
			led_state(1,0,0,1);
			break;
		case 1:
			led_state(1,0,0,0);
			break;
		case 2:
			led_state(0,1,0,0);
			break;
		case 3:
			led_state(0,0,1,0);
			break;
		case 4:
			led_state(0,0,0,1);
			break;
		case 5:
			led_state(2,0,0,0);
			break;
		case 6:
			led_state(0,2,0,0);
			break;
		case 7:
			led_state(0,0,2,0);
			break;
		case 8:
			led_state(0,0,0,2);
			break;
		}
	}
}
//Battery LED Control - Logan
task batteryled() { //Controls battery mode LED states & power level assignments (needs to be split into a constantly running task) (or merge LED tasks into one)
	ledmode=-1; //Used to switch between LED modes with the Debug mode on LCD
	while(ledmode==-1) {
		power=SensorValue[PEPower]/280.0;
		if(nImmediateBatteryLevel/1000.0>=8.5 && power>=8.5) { //Both full, blink LedFull
			while(true) {
				powerlevelCortex=1;
				powerlevelExpander=1;
				led_state(2,0,0,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.5 && power>=8.0){ //Cortex full, PE good; solid Full, blink Green.
			while(true) {
				powerlevelCortex=1;
				powerlevelExpander=0.75;
				led_state(1,2,0,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.5 && power>=7.5) { //Cortex Full, PE OK; Solid Full, blink Yel
			while(true) {
				powerlevelCortex=1;
				powerlevelExpander=0.5;
				led_state(1,0,2,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.5 && power<7.5) { //Cortex Full, PE Bad; Solid Full, Blink Red
			while(true) {
				powerlevelCortex=1;
				powerlevelExpander=0.25;
				led_state(1,0,0,2);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.0 && power>=8.5) { //Cortex Good, PE Full; Solid Green, Blink Full
			while(true) {
				powerlevelCortex=0.75;
				powerlevelExpander=1;
				led_state(2,1,0,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.0 && power>=8.0) { //Cortex Good, PE Good; Blink Green
			while(true) {
				powerlevelCortex=0.75;
				powerlevelExpander=0.75;
				led_state(0,2,0,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.0 && power>=7.5) { //Cortex Good, PE OK; Solid Green, Blink Yel
			while(true) {
				powerlevelCortex=0.75;
				powerlevelExpander=0.5;
				led_state(0,1,2,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=8.0 && power<7.5) { //Cortex Good, PE Bad; Solid Green, Blink Red
			while(true) {
				powerlevelCortex=0.75;
				powerlevelExpander=0.25;
				led_state(0,1,0,2);
			}
			} else if(nImmediateBatteryLevel/1000.0>=7.5 && power>=8.5) { //Cortex OK, PE Full; Solid Yel, Bink Full
			while(true) {
				powerlevelCortex=0.5;
				powerlevelExpander=1;
				led_state(2,0,1,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=7.5 && power>=8.0) { //Cortex OK, PE Good; Solid Yel, Blink Green
			while(true) {
				powerlevelCortex=0.5;
				powerlevelExpander=0.75;
				led_state(0,2,1,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=7.5 && power>=7.5) { //Cortex OK, PE OK; Blink Yel
			while(true) {
				powerlevelCortex=0.5;
				powerlevelExpander=0.5;
				led_state(0,0,2,0);
			}
			} else if(nImmediateBatteryLevel/1000.0>=7.5 && power<7.5) { //Cortex OK, PE Bad; Solid Yel, Blink Red
			while(true) {
				powerlevelCortex=0.5;
				powerlevelExpander=0.25;
				led_state(0,0,1,2);
			}
			} else if(nImmediateBatteryLevel/1000.0<7.5 && power>=8.5) { //Cortex Bad, PE Full; Solid Red, Blink Full
			while(true) {
				powerlevelCortex=0.25;
				powerlevelExpander=1;
				led_state(2,0,0,1);
			}
			} else if(nImmediateBatteryLevel/1000.0<7.5 && power>=8.0) { //Cortex Bad, PE Good; Solid Red, Blink Green
			while(true) {
				powerlevelCortex=0.25;
				powerlevelExpander=0.75;
				led_state(0,2,0,1);
			}
			} else if(nImmediateBatteryLevel/1000.0<7.5 && power>=7.5) { //Cortex Bad, PE OK; Solid Red, Blink Yel
			while(true) {
				powerlevelCortex=0.25;
				powerlevelExpander=0.5;
				led_state(0,0,2,1);
			}
			} else if(nImmediateBatteryLevel/1000.0<7.5 && power<7.5) { //Cortex Bad, PE Bad; Blink Red
			while(true) {
				powerlevelCortex=0.25;
				powerlevelExpander=0.25;
				led_state(0,0,0,2);
			}
		}
	}
}
//LCD Task & Debug Mode - Logan
task lcd { //For LCD Autonomous Selection
	int leftbutton = 1; //aliases for button numbers on LCD
	int centerbutton = 2;
	int rightbutton = 4;
	int leftright = 5;
	int battery = 1;
	int motornum=0;
	int motornummin=0;
	int motornummax=10;
	char motorpower[50];
	while(true) {
		while(debug) { //Debug mode
			int screenmin = 0;
			int screenmax = 5;
			if(nLCDButtons==leftright&&screen==0) {
				debug=false;
				wait1Msec(250);
			}
			if(nLCDButtons==leftbutton) { //Scrolling controls
				if(screen>screenmin) {
					screen--;
					clearLCDLine(0);
					clearLCDLine(1);
					wait1Msec(250);
					} else {
					screen=screenmax;
					clearLCDLine(0);
					clearLCDLine(1);
					wait1Msec(250);
				}
			}
			if(nLCDButtons==rightbutton) { //More Scrolling Controls
				if(screen<screenmax) {
					screen++;
					clearLCDLine(0);
					clearLCDLine(1);
					wait1Msec(250);
					} else {
					screen=screenmin;
					clearLCDLine(0);
					clearLCDLine(1);
					wait1Msec(250);
				}
			}
			switch(screen) {
			case 0:
				displayLCDCenteredString(0,"Debug");
				displayLCDCenteredString(1,"Mode");
				break;
			case 1:
				char batteryvoltage[50];
				if(nLCDButtons==centerbutton) {
					battery=battery*-1;
				}
				switch(battery) {
				case 1:
					sprintf(batteryvoltage, "%1.2f%c", nImmediateBatteryLevel/1000.0);
					displayLCDCenteredString(0,"Cortex");
					displayLCDCenteredString(1,batteryvoltage);
					wait1Msec(250);
					break;
				case -1:
					displayLCDCenteredString(0,"Expander");
					sprintf(batteryvoltage, "%1.2f%c", power/280.0);
					displayLCDCenteredString(1,batteryvoltage);
					wait1Msec(250);
					break;
				}
				break;
			case 2:
				char autotime[5];
				if(autostart==0) {
					displayLCDCenteredString(0,"Run Autonomous?");
				}
				if(nLCDButtons==centerbutton&&autostart!=-1) {
					autostart = -1;
					clearTimer(T1);
					startTask(autonomous);
				}
				if(autostart==-1) {
					sprintf(autotime,"%2.2f",time1[T1]/1000.0);
					displayLCDCenteredString(0,"Running!");
					displayLCDCenteredString(1,autotime);
				}
				displayLCDCenteredString(1,autotime);
				break;
			case 3:
				displayLCDCenteredString(0,"LED Mode");
				if(ledmode==-1) {
					displayLCDCenteredString(1,"Battery");
					} else if(ledmode==1) {
					displayLCDCenteredString(1,"Autonomous");
				}
				if(nLCDButtons==centerbutton) {
					ledmode=ledmode*-1;
					switch(ledmode) {
					case 1:
						stopTask(batteryled);
						startTask(autoled);
						break;
					case -1:
						stopTask(autoled);
						startTask(batteryled);
						break;
					}
					wait1Msec(250);
				}
				break;
			case 4:
				char timerRecord[6];
				if(!recordMode) {
					displayLCDCenteredString(0,"Record Off");
				}
				if(recordMode) {
					displayLCDCenteredString(0,"Record On");
					sprintf(timerRecord,"%3.2f",time1[T3]/1000.0);
					displayLCDCenteredString(1,timerRecord);
				}
				if(nLCDButtons==centerbutton&&!recordMode) {
					recordMode=true;
					clearTimer(T3);
					wait1Msec(250);
				}
				if(nLCDButtons==centerbutton&&recordMode) {
					recordMode=false;
					wait1Msec(250);
				}
				if(time1[T3]/1000.0>recordTime) {
					recordMode=false;
				}
				break;
			case 5:
				if(nLCDButtons==centerbutton) {
					if(motornum<motornummax) {
						motornum++;
						wait1Msec(250);
						} else {
						motornum=motornummin;
						wait1Msec(250);
					}
				}
				switch(motornum) {
				case 0:
					displayLCDCenteredString(0,"Motor Power");
					displayLCDCenteredString(1,"");
					break;
				case 1:
					sprintf(motorpower,"%d",motor[LeftFront]); //Gotta figure out how to convert motor to string.
					displayLCDCenteredString(0,"LeftFront");
					displayLCDCenteredString(1,motorpower);
					break;
				case 2:
					sprintf(motorpower,"%d",motor[LeftBack]);
					displayLCDCenteredString(0,"LeftBack");
					displayLCDCenteredString(1,motorpower);
					break;
				case 3:
					sprintf(motorpower,"%d",motor[RightFront]);
					displayLCDCenteredString(0,"RightFront");
					displayLCDCenteredString(1,motorpower);
					break;
				case 4:
					sprintf(motorpower,"%d",motor[RightBack]);
					displayLCDCenteredString(0,"RightBack");
					displayLCDCenteredString(1,motorpower);
					break;
				case 5:
					sprintf(motorpower,"%d",motor[FLeftTower]);
					displayLCDCenteredString(0,"FLeftTower");
					displayLCDCenteredString(1,motorpower);
					break;
				case 6:
					sprintf(motorpower,"%d",motor[BLeftTower]);
					displayLCDCenteredString(0,"BLeftTower");
					displayLCDCenteredString(1,motorpower);
					break;
				case 7:
					sprintf(motorpower,"%d",motor[FRightTower]);
					displayLCDCenteredString(0,"FRightTower");
					displayLCDCenteredString(1,motorpower);
					break;
				case 8:
					sprintf(motorpower,"%d",motor[BRightTower]);
					displayLCDCenteredString(0,"BRightTower");
					displayLCDCenteredString(1,motorpower);
					break;
				case 9:
					sprintf(motorpower,"%d",motor[ArmLeft]);
					displayLCDCenteredString(0,"ArmLeft");
					displayLCDCenteredString(1,motorpower);
					break;
				case 10:
					sprintf(motorpower,"%d",motor[ArmRight]);
					displayLCDCenteredString(0,"ArmRight");
					displayLCDCenteredString(1,motorpower);
					break;
				}
			}
		}
		while(debug==false) {
			if(nLCDButtons==leftright) {
				debug=true;
				wait1Msec(250);
			}
			if(nLCDButtons==leftbutton) { //Scrolling controls
				if(auto>automin) { //If auto is greater than the minimum, subtract one, otherwise, go to max.
					auto--;
					wait1Msec(250);
					} else {
					auto=automax;
				}	//hi
			}
			if(nLCDButtons==rightbutton) { //More Scrolling Controls
				if(auto<automax) { //If auto is less than the max, add one, otherwise, go to min
					auto++;
					wait1Msec(250);
					} else {
					auto=automin;
				}
			}
			if(nLCDButtons==centerbutton) { //Lock-in selected autonomous and end the task (see task schedule)
				autoselect=1;
			}
			switch(auto) { //Sets the LCD to display the name of selected Autonomous and set the LEDs
			case 0:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(0,"");
				}
				displayLCDCenteredString(1, "Auto Off");
				wait1Msec(100); //These waits keep the LCD from hogging up the Cortex CPU.
				break;
			case 1:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(0,"");
				}
				displayLCDCenteredString(1, "Auto 1");
				wait1Msec(100);
				break;
			case 2:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(0,"");
				}
				displayLCDCenteredString(1, "Auto 2");
				wait1Msec(100);
				break;
			case 3:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(0,"");
				}
				displayLCDCenteredString(1, "Auto 3");
				wait1Msec(100);
				break;
			case 4:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(0,"");
				}
				displayLCDCenteredString(1, "Auto 4");
				wait1Msec(100);
				break;
			case 5:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(1, "");
				}
				displayLCDCenteredString(1, "Auto 5");
				wait1Msec(100);
				break;
			case 6:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(1, "");
				}
				displayLCDCenteredString(1, "Auto 6");
				wait1Msec(100);
				break;
			case 7:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(1, "");
				}
				displayLCDCenteredString(1, "Auto 7");
				wait1Msec(100);
				break;
			case 8:
				if(autoselect==1) {
					displayLCDCenteredString(0,"Selected");
					} else if(autoselect==0) {
					displayLCDCenteredString(1, "");
				}
				displayLCDCenteredString(1,"Auto 8");
				wait1Msec(100);
				break;
			}
		}
	}
}
// Task Schedule - Logan
task scheduler { //Schedules the startup of the bot and user-created tasks
	bLCDBacklight = true;
	startTask(autoled);
	startTask(lcd); //Starts with allowing us to select the autonomous with LCD
	waitUntil(autoselect==1||autostart==1);
	stopTask(lcd);
	stopTask(autoled);
	startTask(batteryled);
}
/////////

//Autonomous// - Keeping pre_auton function nearby for sanity reasons.
void pre_auton()
{
	bStopTasksBetweenModes = false;
	startTask(scheduler);
}
//Autonomous - Logan
task autonomous()
{
	if(debug==false) {
		autostart=1;
	}
	switch(auto) { //Runs different autonomous based on the value of 'auto'
	case 0: //This is if we want to disable autonomous; when auto == 0, do nothing.
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 1:
		interpretAuto(auto1String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 2:
		interpretAuto(auto2String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 3:
		interpretAuto(auto3String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 4:
		interpretAuto(auto4String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 5:
		interpretAuto(auto5String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 6:
		interpretAuto(auto6String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 7:
		interpretAuto(auto7String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	case 8:
		interpretAuto(auto8String);
		if(autostart==-1) {
			autostart=0;
		}
		break;
	}
}
////////////////////////

//User Control// - Please don't be stupid(like me) and make sure that everything control-related is in the while() loop.
// - Logan & Carmen
task usercontrol() {
	while (true) {
		if(!debug) { //Normal Controls when not in Debug mode.
			moveLeft(vexRT[Ch3]); //LeftDrive controls
			moveRight(vexRT[Ch2]); //RightDrive controls
			//Tower controls
			if(vexRT[Btn6U] == 1) { //Tower one controls (left from front)
				manipulator_tower(127);
				} else if(vexRT[Btn6D] == 1) { //Tower two controls (right from front)
				manipulator_tower(-127);
				} else { //Stop towers if nothing is pressed
				manipulator_tower(0);
			}

			//Arm controls
			if(vexRT[Btn5D] == 1) {
				manipulator_arm(30);
				} else if(vexRT[Btn5U] == 1) {//Extend Outwards
				manipulator_arm(-90);
				}	else{ //Stop arms if nothing is pressed
				manipulator_arm(0);
			}
		}

		if(debug) { //Conditional Controls for Debug Mode.
			if(screen==4) { //RecordAuto controls
				if(recordTime>time1[T3]/1000.0) {
					moveLeft(vexRT[Ch3]); //LeftDrive controls
					moveRight(vexRT[Ch2]); //RightDrive controls
					//Tower controls
					if(vexRT[Btn6U] == 1) { //Tower one controls (left from front)
						recordAuto('a')

						;
						manipulator_tower(127);
						} else if(vexRT[Btn6D] == 1) { //Tower two controls (right from front)
						recordAuto('b');
						manipulator_tower(-127);
						} else { //Stop towers if nothing is pressed
						recordAuto('c');
						manipulator_tower(0);
					}

					//Arm controls
					if(vexRT[Btn5D] == 1) {
						recordAuto('i');
						manipulator_arm(30);
						} else if(vexRT[Btn5U] == 1) {//Extend Outwards
						recordAuto('j');
						manipulator_arm(-90);
						}	else{ //Stop arms if nothing is pressed
						recordAuto('k');
						manipulator_arm(0);
					}
				}
				if(recordTime<time1[T3]/1000.0) {
					allMotorsOff();
				}
			}
		}
		//RecordAuto Channel Statements
		if(motor[LeftFront]>0) {
			recordAuto('d');
		}
		if(motor[LeftFront]<0) { //When left motor is negative, print 'e' to debug stream.
			recordAuto('e');
		}
		if(motor[RightFront]>0) { //When right motor is positive, print 'f' to debug stream.
			recordAuto('f');
		}
		if(motor[RightFront]<0) { //When right motor is negative, print 'g' to debug stream.
			recordAuto('g');
		}
		if(motor[RightFront]==0 && motor[LeftFront]==0) { //When left and right motors are off, print 'z' to debug stream (so interpretAuto knows to do nothing)
			recordAuto('h');
		}
	}
}
