#pragma config(Sensor, in1,    J1,             sensorAnalog)
#pragma config(Sensor, in2,    J2,             sensorAnalog)
#pragma config(Sensor, in3,    J3,             sensorAnalog)
#pragma config(Sensor, in4,    J4,             sensorAnalog)
#pragma config(Sensor, in5,    J5,             sensorAnalog)
#pragma config(Sensor, in6,    J6,             sensorAnalog)
#pragma config(Sensor, in7,    J7,             sensorAnalog)
#pragma config(Sensor, in8,    J8,             sensorAnalog)
#pragma config(Sensor, dgtl1,  PEPower,        sensorDigitalIn)
#pragma config(Sensor, dgtl9,  LedRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, LedYel,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, LedGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, LedFull,        sensorLEDtoVCC)
#pragma config(Motor,  port1,           ArmRight,      tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           RightBack,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LeftBack,      tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           BRightTower,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           FRightTower,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           FLeftTower,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           BLeftTower,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           RightFront,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port9,           LeftFront,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          ArmLeft,       tmotorVex393_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// ---------- Functions ---------- //
//function cap is 256, do not exceed this limit

void move_pivot_turn(int time, int power) { //Right Turn in place (pos. power = left, neg. = right) ---> 90 degree turn
	motor[LeftFront] = power;
	motor[LeftBack] = power;
	motor[RightFront] = power*-1;
	motor[RightBack] = power*-1;
	wait1Msec(time);
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;
	motor[RightFront] = 0;
	motor[RightBack] = 0;
}
void move_swing_turn(int time, int lpower, int rpower) { //Adjustable Angle Turns (allows for swing turns by setting one value higher than the other)
	motor[LeftFront] = lpower;
	motor[LeftBack] = lpower;
	motor[RightFront] = rpower;
	motor[RightBack] = rpower;
	wait1Msec(time);
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;
	motor[RightFront] = 0;
	motor[RightBack] = 0;
}
void move_straight(int time, int power) { //Move straight (positive for forward, negative for reverse)
	motor[LeftFront] = power;
	motor[LeftBack] = power;
	motor[RightFront] = power;
	motor[RightBack] = power;
	wait1Msec(time);
	motor[LeftFront] = 0;
	motor[LeftBack] = 0;
	motor[RightFront] = 0;
	motor[RightBack] = 0;
}
void move(int lpower,int rpower) {
	motor[LeftFront] = lpower;
	motor[LeftBack] = lpower;
	motor[RightFront] = rpower;
	motor[RightBack] = rpower;
}

void manipulator_tower(int time, int power) { //Raise/Lower Arm Tower
	motor[FLeftTower] = power;
	motor[BLeftTower] = power;
	motor[BRightTower] = power;
	motor[FRightTower] = power;
	wait1Msec(time);
	motor[FLeftTower] = 0;
	motor[BLeftTower] = 0;
	motor[BRightTower] = 0;
	motor[FRightTower] = 0;
}
void manipulator_arm(int time, int power) { //Raise/Lower Arm
	motor[ArmLeft] = power;
	motor[ArmRight] = power;
	wait1Msec(time);
	motor[ArmLeft] = 0;
	motor[ArmRight] = 0;
}
void dab(int time, int power) {
	manipulator_tower(600,127);//#EpicGamesWinSlay2018
	move_pivot_turn(time, power);
	move_pivot_turn(time, -power);
	move_swing_turn(time, power, power*-1);
}
void stop_all() {
	motor[ArmLeft] = 0;
	motor[ArmRight] = 0;
	motor[BLeftTower] = 0;
	motor[BRightTower] = 0;
	motor[FLeftTower] = 0;
	motor[FRightTower] = 0;
	motor[LeftBack] = 0;
	motor[LeftFront] = 0;
	motor[RightBack] = 0;
	motor[RightFront] = 0;
}
// ------------------------------- //

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = false;
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
task batterycontrol()
{
	while(true) {
		float power=SensorValue[PEPower]/270.0;
		if(nImmediateBatteryLevel/1000>=8.5 && power>=8.5) { //Both full, blink LedFull
			while(true) {
				SensorValue[LedGreen]=0;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=0;
				SensorValue[LedFull]=1;
				wait1Msec(500);
				SensorValue[LedFull]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.5 && power>=8.0){ //Cortex full, PE good; solid Full, blink Green.
			while(true) {
				SensorValue[LedFull]=1;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=0;
				SensorValue[LedGreen]=1;
				wait1Msec(500);
				SensorValue[LedGreen]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.5 && power>=7.5) { //Cortex Full, PE OK; Solid Full, blink Yel
			while(true) {
				SensorValue[LedFull]=1;
				SensorValue[LedGreen]=0;
				SensorValue[LedRed]=0;
				SensorValue[LedYel]=1;
				wait1Msec(500);
				SensorValue[LedYel]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.5 && power<7.5) { //Cortex Full, PE Bad; Solid Full, Blink Red
			while(true) {
				SensorValue[LedFull]=1;
				SensorValue[LedGreen]=0;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=1;
				wait1Msec(500);
				SensorValue[LedRed]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.0 && power>=8.5) { //Cortex Good, PE Full; Solid Green, Blink Full
			while(true) {
				SensorValue[LedGreen]=1;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=0;
				SensorValue[LedFull]=1;
				wait1Msec(500);
				SensorValue[LedFull]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.0 && power>=8.0) { //Cortex Good, PE Good; Blink Green
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=0;
				SensorValue[LedGreen]=1;
				wait1Msec(500);
				SensorValue[LedGreen]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.0 && power>=7.5) { //Cortex Good, PE OK; Solid Green, Blink Yel
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedGreen]=1;
				SensorValue[LedRed]=0;
				SensorValue[LedYel]=1;
				wait1Msec(500);
				SensorValue[LedYel]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=8.0 && power<7.5) { //Cortex Good, PE Bad; Solid Green, Blink Red
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedGreen]=1;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=1;
				wait1Msec(500);
				SensorValue[LedRed]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=7.5 && power>=8.5) {
			while(true) {
				SensorValue[LedGreen]=0;
				SensorValue[LedYel]=1;
				SensorValue[LedRed]=0;
				SensorValue[LedFull]=1;
				wait1Msec(500);
				SensorValue[LedFull]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=7.5 && power>=8.0) {
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedYel]=1;
				SensorValue[LedRed]=0;
				SensorValue[LedGreen]=1;
				wait1Msec(500);
				SensorValue[LedGreen]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=7.5 && power>=7.5) {
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedGreen]=0;
				SensorValue[LedRed]=0;
				SensorValue[LedYel]=1;
				wait1Msec(500);
				SensorValue[LedYel]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000>=7.5 && power<7.5) {
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedGreen]=0;
				SensorValue[LedYel]=1;
				SensorValue[LedRed]=1;
				wait1Msec(500);
				SensorValue[LedRed]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000<7.5 && power>=8.5) {
			while(true) {
				SensorValue[LedGreen]=0;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=1;
				SensorValue[LedFull]=1;
				wait1Msec(500);
				SensorValue[LedFull]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000<7.5 && power>=8.0) {
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=1;
				SensorValue[LedGreen]=1;
				wait1Msec(500);
				SensorValue[LedGreen]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000<7.5 && power>=7.5) {
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedGreen]=0;
				SensorValue[LedRed]=1;
				SensorValue[LedYel]=1;
				wait1Msec(500);
				SensorValue[LedYel]=0;
				wait1Msec(500);
			}
			} else if(nImmediateBatteryLevel/1000<7.5 && power<7.5) {
			while(true) {
				SensorValue[LedFull]=0;
				SensorValue[LedGreen]=0;
				SensorValue[LedYel]=0;
				SensorValue[LedRed]=1;
				wait1Msec(500);
				SensorValue[LedRed]=0;
				wait1Msec(500);
			}
		}
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	//if(SensorValue[J1] == 1) { //Flag Tile (FT), Red Team, Tile Parking
	//	//move_pivot_turn(1000,-127);//Turn Left
	//	//move_straight(1000,127); //Go forward 2 tiles
	//	//move_pivot_turn(2000,127);//Turn 180 Degress Right (Turn Around)
	//	//move_straight(2000,127); //Go forward 2 tiles
	//}
	//if(SensorValue[J2] == 1) { //FT, Blue Team, Tile
	//	//move_pivot_turn(1000,127);//Turn Right
	//	//move_straight(2000,127); //Go forward 2 tiles
	//	//move_pivot_turn(2000,-127);//Turn 180 Degress Left (Turn Around)
	//	//move_straight(2000,127); //Go forward 2 tiles
	//}
	//if(SensorValue[J3] == 1) { //FT, Red Team, Platform Parking
	//	//manipulator_arm(1000,127);//Move arm up
	//	//manipulator_arm(1000,-127);//and back down
	//}
	//if(SensorValue[J4] == 1) { //FT, Blue Team, Platform
	//	//move_pivot_turn(1000,127);//Turn Right
	//	//move_straight(1000,127); //Go to middle of next tile
	//	//move_pivot_turn(1000,-127);//Turn Left
	//	//move_straight(2000,127);//Go to middle platform
	//}
	//if(SensorValue[J5] == 1) { //Opposite Tile (OT), Red Team, Tile
	//	//move_straight(1000,127); //placeholder until 'real' code is made.
	//	}
	//if(SensorValue[J6] == 1) { //OT, Blue Team, Tile
	//	//move_straight(1000,127); //placeholder until 'real' code is made.
	//}
	//if(SensorValue[J7] == 1) { //OT, Red Team, Platform
	//	//move_straight(1,127); //placeholder until 'real' code is made.
	//}
	//if(SensorValue[J8] == 1) { //OT, Blue Team, Platform
	//	//move_straight(1,127); //placeholder until 'real' code is made.
	//}
	//else {
	//	//dab(300,127);//Dice Dab
	//	//stop_all();
	//}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	startTask(batterycontrol);
	while (true)
	{
		motor[RightFront] = vexRT[Ch3]; //Left Front motor to left joystick
		motor[RightBack] = vexRT[Ch3]; //Left Back motor to left joystick
		motor[LeftFront] = vexRT[Ch2]; //Right Front to right joystick
		motor[LeftBack] = vexRT[Ch2]; //Right Back to right joystick

		//Tower controls
		if(vexRT[Btn6U] == 1) { //Tower one controls (left from front)
			motor[FLeftTower] = 127; //FLeft = Left front tower motor, BRight = Back right tower motor
			motor[BLeftTower] = 127;
			motor[BRightTower] = 127;
			motor[FRightTower] = 127;
			} else if(vexRT[Btn6D] == 1) { //Tower two controls (right from front)
			motor[FLeftTower] = -127;
			motor[BLeftTower] = -127;
			motor[BRightTower] = -127;
			motor[FRightTower] = -127;
			} else { //Stop towers if nothing is pressed
			motor[FLeftTower] = 0;
			motor[BLeftTower] = 0;
			motor[BRightTower] = 0;
			motor[FRightTower] = 0;
		}

		if(vexRT[Btn7U] == 1) { //Tower Up Button
			manipulator_tower(300, 127);
			} else if(vexRT[Btn7D] == 1) { //Tower Down Button
			manipulator_tower(300,-127); //Hopefully this works... and doesn't break anything. =)
		}

		//Arm controls
		if(vexRT[Btn5U] == 1) {
			motor[ArmLeft] = 30;
			motor[ArmRight] = 30;
			} else if(vexRT[Btn5D] == 1) {//Extend Outwards
			motor[ArmLeft] = -90;
			motor[ArmRight] = -90;
			}	else{ //Stop arms if nothing is pressed
			motor[ArmLeft] = 0;
			motor[ArmRight] = 0;
		}

	//	//Battery Lights
	//	if(nImmediateBatteryLevel/1000>=8.5) {
	//		SensorValue[LedFull]=1;
	//		SensorValue[LedGreen]=1;
	//		SensorValue[LedRed]=0;
	//		SensorValue[LedYel]=0;
	//		} else if(nImmediateBatteryLevel/1000>=8.0){
	//		SensorValue[LedFull]=0;
	//		SensorValue[LedGreen]=1;
	//		SensorValue[LedRed]=0;
	//		SensorValue[LedYel]=0;
	//		} else if(nImmediateBatteryLevel/1000>=7.5){
	//		SensorValue[LedFull]=0;
	//		SensorValue[LedGreen]=0;
	//		SensorValue[LedRed]=0;
	//		SensorValue[LedYel]=1;
	//		} else if(nImmediateBatteryLevel/1000<7.5){
	//		SensorValue[LedFull]=0;
	//		SensorValue[LedGreen]=0;
	//		SensorValue[LedRed]=1;
	//		SensorValue[LedYel]=0;
	//	}
	}
}
